Repository AY2122S1-CS2103T-W08-4/tp, pull requests merged in 2021-11, with the labels that each got.

#259 Add Input Suggestion to DG
  docs/DeveloperGuide.md
Labels: documentation.DG

#260 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation.UG

#206 Update UserGuide with Deletet and Addt
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation.UG

#258 Update UG
  docs/UserGuide.md
Labels: documentation.UG

#332 Fix find command bug for social handle
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/SocialHandle.java
  src/main/java/seedu/address/model/person/predicate/SocialHandleContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/predicate/SocialHandleContainsKeywordsPredicateTest.java
Labels: type.Bug, severity.High

#272 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditCommandDiagramForSocialHandle.puml
  docs/images/dg/EditCommandDiagramForSocialHandle.png
  docs/images/dg/SocialHandleBeforeAfter.png
Labels: documentation.DG

#314 Add stats command to DG
  docs/DeveloperGuide.md
  docs/diagrams/StatisticParserSequenceDiagram.puml
  docs/diagrams/StatisticSequenceDiagram.puml
  docs/images/StatisticParserSequenceDiagram.png
  docs/images/StatisticSequenceDiagram.png
  src/main/java/seedu/address/model/statistic/Statistic.java
Labels: documentation.DG

#328 Update UserGuide.md
  docs/UserGuide.md
  docs/images/AddErnest.png
Labels: documentation.UG
