Repository AY2122S1-CS2103T-W08-4/tp, pull requests merged in 2021-10, with the labels that each got.

#49 Aboutus
  docs/AboutUs.md
  docs/images/choonyongchan.png
  docs/images/e0543978.png
  docs/images/hsiaotingluv.png
  docs/images/kevinmingtarja.png
Labels: documentation.PW

#60 Update 'Find' Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/MultiplePredicates.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NationalityContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TutorialGroupContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NationalityContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TutorialGroupContainsKeywordsPredicateTest.java
Labels: priority.High

#108 Reformat documentation for implementation
  docs/DeveloperGuide.md
Labels: documentation.DG

#113 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation.DG

#110 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation.UG

#116 Bold command word
  docs/UserGuide.md
Labels: documentation.UG

#119 Bold all command word
  docs/UserGuide.md
Labels: documentation.UG

#112 Update index.md
  docs/index.md
Labels: documentation.PW

#257 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation.UG
